isInterpretingEmptyObjectsAsDictionaries: true
pluralizationExceptions: ["ConfigWas", "EventsWere"]
paths:
  overrideResponses:
    accepted: "Void"
entities:
  isUsingCustomCodingKeys: true
rename:
  enumCaseNames:
    reactions-+1: "reactionsPlusOne"
    reactions--1: "reactionsMinusOne"
